version: '3'
services:
    node:
        build: 
            context: .
            dockerfile: NodeDockerfile
        volumes:
            - ./build:/usr/src/app/build
    nginx:
        build: 
            context: .
            dockerfile: NginxDockerfile
        volumes: 
            - ./build:/var/www
            - /etc/letsencrypt:/etc/letsencrypt
        command: "nginx -g 'daemon off;'"
        ports:
            - 80:80
            - 443:443
        depends_on:
            - node
